apiVersion: v1
kind: Service
metadata:
  name: berget
  namespace: berget
spec:
  ports:
    - port: 80
  type: ClusterIP
  selector:
    app: berget
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: berget
  namespace: berget
spec:
  replicas: 2
  selector:
    matchLabels:
      app: berget
  template:
    metadata:
      labels:
        app: berget
    spec:
      containers:
        - name: berget
          image: ghcr.io/berget-cloud/website:0.1.22 # {"$imagepolicy": "berget:berget"}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
