apiVersion: apps/v1
kind: Deployment
metadata:
  name: berget-deployment
  namespace: berget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: berget
  template:
    metadata:
      labels:
        app: berget
    spec:
      containers:
        - name: berget
          image: ghcr.io/berget/berget:main
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: berget-service
  namespace: berget
spec:
  selector:
    app: berget
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berget-ingress
  namespace: berget
spec:
  rules:
    - host: berget.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: berget-service
                port:
                  number: 3000
